fail ci if license check finds missing file headers

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,10 +17,6 @@ jobs:
       - name: Check for TODO statements
         run: (find . -iname "*.cs" -exec grep -qi "todo" {} \; -print) > ./todo_log.txt
 
-
-      - name: Check for Apache Licnse headers
-        run: (find . \( -path "./git*" -o -name "README.md" \) -prune -o -type f -iname "*.cs" -exec grep -L "Apache License" {} \;) > ./license_log.txt
-
       - name: Save todo log
         if: success()
         uses: actions/upload-artifact@v3
@@ -28,12 +24,18 @@ jobs:
           name: todologs  # Specify the name for your artifact
           path: ./**/todo_log.txt  # Replace with the actual path to your generated JSON file
 
+      - name: Check for Apache Licnse headers
+        run: (find . \( -path "./git*" -o -name "README.md" \) -prune -o -type f -iname "*.cs" -exec grep -L "Apache License" {} \;) > ./license_log.txt
+
       - name: Save license log
         if: success()
         uses: actions/upload-artifact@v3
         with:
           name: licenselogs  # Specify the name for your artifact
           path: ./**/license_log.txt  # Replace with the actual path to your generated JSON file
+
+      - name: Fail if no headers
+        run: if [ -s "./license_log.txt"]; then echo "Some files are missing the license header"; exit 1; fi
 
 
 
